CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = vecInt.exe vecStr.exe vecTest.exe vecToupper.exe sum.exe \
	  iterator.exe toUpper.exe
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
