CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = const.exe identifier.exe syntaxError.exe typeConvert.exe typeDefine.exe
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
